### ISSUE TITLE
réaliser les maquettes

### ISSUE THREAD

**Issue by G-Houlmann** [G-Houlmann/Site-EPM-GRV#1]

**Comment by Schneiter924** [comment]
[menuPrincipal.pdf](https://github.com/G-Houlmann/Site-EPM-GRV/files/1296014/menuPrincipal.pdf)

**Comment by Schneiter924** [comment]
[menuPrincipal.pdf](https://github.com/G-Houlmann/Site-EPM-GRV/files/1296039/menuPrincipal.pdf)
